apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: safra-redis-data
  labels:
    app.kubernetes.io/name: safra-ia-ops
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName: gp3  # descomente e ajuste conforme o cluster OpenShift
